mechdb/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include('mechdb_core.urls')),
]

mechdb_core/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.auth.decorators import login_required

urlpatterns = [

    url(r'^user/password/reset/$', PasswordResetView.as_view(),
        {'post_reset_redirect': '/user/password/reset/done/'},
        name="password_reset"),
    url(r'^user/password/reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^user/password/done/$',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^terms_of_use/$', views.terms_of_use, name='terms_of_use'),
    url(r'^privacy_policy/$', views.privacy_policy, name='privacy_policy'),
    url(r'^login/$', views.signin, name='signin'),
    url(r'^login/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^guide/$', views.guide, name='guide'),
    url(r'^$', views.index_page, name='index_page'),
    # === контейнеры ===
    url(r'^map/', views.containers_map, name='containers_map'),
    url(r'^place/(?P<pk>\d+)/$', views.container_detail, name='container_detail'),
    url(r'^place/new/$', views.container_new, name='container_new'),
    url(r'^place/(?P<pk>\d+)/edit/$', views.container_edit, name='container_edit'),
    url(r'^place/(?P<pk>\d+)/remove/$', views.container_remove, name='container_remove'),
    # === оборудование ===
    url(r'^equipment/list/$', views.equipment_list, name='equipment_list'),
    url(r'^equipment/(?P<pk>\d+)/$', views.equipment_detail, name='equipment_detail'),
    url(r'^equipment/new/$', views.equipment_new, name='equipment_new'),
    url(r'^equipment/(?P<pk>\d+)/edit/$', views.equipment_edit, name='equipment_edit'),
    url(r'^equipment/(?P<pk>\d+)/remove/$', views.equipment_remove, name='equipment_remove'),
    # === типоразмеры ===
    url(r'^model/list/$', views.sizename_list, name='sizename_list'),
    url(r'^model/(?P<pk>\d+)/$', views.sizename_detail, name='sizename_detail'),
    url(r'^model/new/$', views.sizename_new, name='sizename_new'),
    url(r'^model/(?P<pk>\d+)/edit/$', views.sizename_edit, name='sizename_edit'),
    url(r'^model/(?P<pk>\d+)/remove/$', views.sizename_remove, name='sizename_remove'),
    # === action ===
    url(r'^action/all/$', views.action_list, name='action_list'),
    url(r'^action/(?P<pk>\d+)/$', views.action_detail, name='action_detail'),
    url(r'^action/new/$', views.action_new, name='action_new'),
    url(r'^action/(?P<pk>\d+)/edit/$', views.action_edit, name='action_edit'),
    url(r'^action/(?P<pk>\d+)/remove/$', views.action_remove, name='action_remove'),
    # === ajax ===
    url(r'^testurl/$', views.testview, name='testview'),
    url(r'^get_objects_tree/$', login_required(views.get_objects_tree), name='get_objects_tree'),
    url(r'^get_actions_list/$', login_required(views.get_actions_list), name='get_actions_list'),
]

mechdb_core/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date, time
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

@receiver(post_save, sender=User)
def new_user(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Container(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    title = models.CharField(max_length=200, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    is_repair_organization = models.BooleanField(default=False, blank=False, null=False)
    in_container = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self):
        return str(self.pk)+" "+str(self.owner)+" "+self.title

class Equipment_sizename(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    title = models.CharField(max_length=200, blank=False, null=False, verbose_name="Наименование")

    sizename_type_choices = (
                ('pump', "Насос"),
                ('compressor', "Компрессор"),
                ('bench', "Станок"),
                ('e-engine', "Электродвигатель"),
                ('engine', "ДВС"),
                ('turbine', "Турбина"),
                ('crane', "ГПМ"),
                ('air-handling-unit', "Вент. установка"),
                ('air-cooling-unit', "АВО"),
                ('heat-exchanger', "Теплообменник"),
                ('furnace', "Печь"),
                ('safe-valve', "Клапан предохр."),
                ('check-valve', "Клапан обратный"),
                ('control-valve', "Задвижка, клапан реглирующий"),
                ('other', "Прочее оборудование"),
                )
    type = models.CharField(max_length=25,choices=sizename_type_choices,default='other', verbose_name="Тип оборудования")
    manufacturer = models.CharField(max_length=100, blank=False, null=False, default='н/д', verbose_name="Производитель")
    supply_provider = models.CharField(max_length=100, blank=False, null=False, default='н/д', verbose_name="Поставщик")
    def __str__(self):
        return self.title

class Equipment(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    sizename = models.ForeignKey(Equipment_sizename, on_delete=models.CASCADE, blank=False, null=False)
    serial_number = models.CharField(max_length=50, blank=True, null=True)
    registration_number = models.CharField(max_length=50, blank=True, null=True)
    in_container = models.ForeignKey(Container, on_delete=models.CASCADE, blank=False, null=False)
    def __str__(self):
        return str(self.sizename.title)+" № "+str(self.serial_number)+'  ['+self.in_container.title+']'

    def set_correct_places(self):
        # функция корректной проставки used_in_container
        # НЕ ЗАБЫТЬ  - расход может применяться на оборудование. при этом не очень понятно что будет делать данная функция с такими расходами
        actions = Action.objects.filter(used_in_equipment=self).order_by("action_start_date")
        new_container = None
        for action in actions:
            action.used_in_container.clear()
            if new_container:
                action.used_in_container.add(new_container)
            if action.new_container:
                new_container = action.new_container
                action.used_in_container.add(new_container)
        if new_container:
            self.in_container = new_container
            self.save()


class Spare_part(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    title = models.CharField(max_length=200, blank=False, null=False)
    unit_name = models.CharField(max_length=10, blank=False, null=False)
    in_container = models.ForeignKey(Container, on_delete=models.SET_NULL, blank=True, null=True)
    used_in_equipment = models.ManyToManyField(Equipment_sizename)
    manufacturer = models.CharField(max_length=100, blank=False, null=False, default='н/д')
    suply_provider = models.CharField(max_length=100, blank=False, null=False, default='н/д')
    def __str__(self):
        return self.title

class Action(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    action_type_choices_equipment = (
                ('equipment,repair,TO', "ТО"),
                ('equipment,repair,TR', "ТР"),
                ('equipment,repair,KR', "КР"),
                ('equipment,repair,KTS', "КТС"),
                ('equipment,repair,DEFF', "ремонт"),
                ('equipment,INFO', "информация"),
                ('equipment,FAILURE', "отказ"),
                ('equipment,REPAIR_EXPORT', "вывоз в ремонт"),
                ('equipment,REPAIR_IMPORT', "завоз с ремонта"),
                ('equipment,MOUNT', "монтаж"),
                ('equipment,UNMOUNT', "демонтаж"),
                ('equipment,MOVE', "перемещение")
                )
    action_type_choices_spare_parts = (
                ('action,INFO', "информация"),
                ('action,MOVE', "перемещение")
                )
    action_type_choices_childs = (
                ('child,OUTGO', "расход"),
                )
    action_type_choices_all = action_type_choices_equipment + action_type_choices_spare_parts + action_type_choices_childs
    type = models.CharField(max_length=25,choices=action_type_choices_all,default='equipment,INFO')
    action_start_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    action_end_date = models.DateTimeField(default=timezone.now, blank=False, null=False)
    scheduled = models.NullBooleanField(default=None)
    description = models.TextField(blank=True, null=True)
    used_in_equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, blank=True, null=True)
    used_in_action = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    used_in_spare_part = models.ForeignKey(Spare_part, on_delete=models.CASCADE, blank=True, null=True)
    used_in_container = models.ManyToManyField(Container, blank=True, related_name='used_in_container')
    quantity_delta = models.FloatField(default=None, blank=True, null=True)
    new_container = models.ForeignKey(Container, on_delete=models.CASCADE, blank=True, null=True, related_name='new_container')

    def __str__(self):
        return self.get_type_display()+' '+ str(self.used_in_equipment)

mechdb_core/templates/mechdb_core/action_detail.html
{% extends 'mechdb_core/base.html' %}

{% block content %}
      <h1><center>Карточка воздействия</center></h1>
      <div class='card_page col-md-7 col-centered'>
          <div class="btn-group pull-right">
                  <button type="button" class="btn btn-warning">Действия</button>
                  <button type="button" class="btn btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'action_edit' pk=action.pk%}">Редактировать</a>
                        <a class="dropdown-item" href="{% url 'action_remove' pk=action.pk%}">Удалить</a>
                  </div>
          </div>
          <UL>
              <LI>
                <b>Тип воздействия:</b> {{action.get_type_display}}
                {% if action.scheduled is True %}
                <font color='green'>(плановое)</font>
                {% elif action.scheduled is False %}
                <font color='red'>(внеплановое)</font>
                {% endif %}

              </LI>
              <LI>
                <b>Дата воздействия:</b> {{ action.action_start_date|date:"d.m.Y H:i" }}
              </LI>
              {% if action.action_end_date and action.action_end_date != action.action_start_date%}
              <LI>
                <b>Дата окончания:  </b> {{ action.action_end_date|date:"d.m.Y H:i" }}
              </LI>
              {% endif %}
              <LI>
                <b>Оборудование:</b>
                <a class="href-red" href="{% url 'equipment_detail' pk=action.used_in_equipment.pk %}">{{ action.used_in_equipment.sizename.title }} № {{ action.used_in_equipment.serial_number }}</a>
              </LI>
              <LI>
                <b>Проводилось в контейнере:</b><br>
                        <!-- аналогичный код в equipment_detail -->
                        {% if action.new_container %}
                                {% if action.used_in_container.all.0.pk == action.new_container.pk %}
                                    <a class="containerhref" href="{% url 'container_detail' pk=action.used_in_container.last.pk %}">
                                    {{action.used_in_container.all.1.title}}
                                    </a>
                                {% else %}
                                    <a class="containerhref" href="{% url 'container_detail' pk=action.used_in_container.all.0.pk %}">
                                    {{action.used_in_container.all.0.title}}
                                    </a>
                                {% endif %}
                            <i class="fa fa-long-arrow-right"></i>
                            <b><a class="containerhref" href="{% url 'container_detail' pk=action.new_container.pk %}">
                            {{action.new_container.title}}
                            </a></b>
                        {% else %}
                            {% if action.used_in_container.last.in_container %}
                                <a class="containerhref" href="{% url 'container_detail' pk=action.used_in_container.last.in_container.pk %}">
                                {{ action.used_in_container.last.in_container.title }}
                                </a>
                                <i class="fa fa-angle-left"></i>
                            {% endif %}
                            {% if action.used_in_container.last %}
                                <b><a class="containerhref" href="{% url 'container_detail' pk=action.used_in_container.last.pk %}">
                                {{ action.used_in_container.last.title }}
                                </a></b>
                            {% endif %}
                        {% endif %}
              </LI>
              <LI>
                <b>Описание:</b><br>
                {{action.description|linebreaks}}
              </LI>
          </UL>
      </div>
{% endblock %}

mechdb_core/templates/mechdb_core/action_edit.html
{% extends 'mechdb_core/base.html' %}

{% block content %}
      <center><h1>{{ form.label }}</h1></center>
      <font class='equipmenthref'><center><h4>{{ form.object }}</h4></center></font>
      <div class="card_page col-md-7 col-centered">
      <form method="POST" class="post-form">{% csrf_token %}
          {{ form.as_p }}
          &nbsp;<br>
          &nbsp;<br>
          <button type="submit" class="save btn btn-default">Сохранить</button>
      </form>
      </div>

{% endblock %}

mechdb_core/templates/mechdb_core/base.html
{% load static %}
<!DOCTYPE html>


<HTML lang="ru">
  <HEAD>
    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/static/img/favicon.ico"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yeseva+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">

    <script src="http://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mechdb_core.css' %}">

    {% include "./counters.html" %}
    {% if page_title %}
    <TITLE>{{page_title}} | MechDB.info</TITLE>
    {% else %}
    <TITLE>MechDB.info - сервис учёта проведения ремонтов динамического оборудования</TITLE>
    {% endif %}
    <meta name="keywords" content="оборудование,динамическое,учёт,ремонт,сервис,ЗИП">
    <meta name="description" content="Сервис учёта провдения ремонтов и обслуживания динамического оборудования">

    {% block scripts %}
    {% endblock %}

  </HEAD>
  <BODY style="background-color:#A6A6A6;">
        {% csrf_token %}

        <div class="page-header container">
          <div class="title-block col-md-8">
            <h1 id="sitetitle"><a href="/">MechDB.info</a></h1>
            {% include "./dropdown_menu.html" %}
          </div>
          {% if not authorization_hide %}
              <div class="col-md-4 login-window">
                {% if current_user.username %}
                    <!-- Пользователь не авторизован -->
                    <p id="greetings">Привет, <FONT color="blue">{{ current_user.username }}</FONT> <i class="fa fa-user"></i><br>
                    Уведомления: 0<br>
                    <a class="logout-href" href="{% url 'logout_view' %}">Выход</a></p>
                {% else %}
                    <!-- Пользователь авторизован -->
                    <form id="form" name="form" method="post" action="{% url 'signin' %}">
                        {% csrf_token %}
                        <div id="loginformblock">
                          <label class="login-label" for="name"><i class="login-icon fa fa-user fa-lg"></i></label><input class="login-input" type="text" name="name" id="name" placeholder="Логин" required/>
                          <label class="login-label" for="name"><i class="login-icon fa fa-lock fa-lg"></i></label><input class="password-input" type="password" name="password" id="password" placeholder="Пароль" required /><button class="login-submit" type="submit" /><i class="login-icon fa fa-arrow-right fa-lg"></i></button>
                          <p id="login-forgotpass"><a id="login-forgotpass-href" href="{% url 'password_reset' %}">Забыли пароль?</a></p>
                        </div>
                    </form>
                {% endif %}
              </div>
          {% endif %}

        </div>

      <div class="content container">
          <div class="row">
              {% block content %}
              {% endblock %}
          </div>
      </div>

      <div class="footer container">
            <p id="footer-text">
            <b>Copyright 2018 MechDB.info by Hadmi</b><br>
            Все права защищены. Запрещено использование, модификация материалов или<br>
            исходного кода ресурса без явного разрешения автора
            </p>
      </div>

      <!-- СКРИПТ ОБРАБОТКИ ТУЛТИПОВ -->
      <script type="text/javascript">
      $(function () {
          $("[rel='tooltip']").tooltip();
      });
      </script>
      <!-- СКРИПТ ОБРАБОТКИ ТУЛТИПОВ -->

      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
  </BODY>
</HTML>

mechdb_core/templates/mechdb_core/container_edit.html
{% extends 'mechdb_core/base.html' %}

{% block content %}
      <center><h1>{{ form.label }}</h1></center>
      <div class='card_page col-md-7 col-centered'>
      <form method="POST" class="post-form">{% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="save btn btn-default">Сохранить</button>
      </form>
      </div>
{% endblock %}

mechdb_core/templates/mechdb_core/container_remove.html
{% extends 'mechdb_core/base.html' %}

{% block content %}
    <div class="card_page col-md-8 col-centered">
      {% if childs %}
      <center><h3>Удаление невозможно</h3></center>
      Обнаружены объекты, содержащиеся в удаляемом контейнере <a class="href-red" href="{% url 'container_detail' pk=container.pk %}"><b>{{container.title}}</b></a>.<br>
      Для того, чтобы удалить контейнер, сначала переместите или удалите следующие объекты:<br>
      <br>

      {% if child_containers %}
      <b>Контейнеры</b>
      <UL>
        {% for i in child_containers %}
        <LI>
          <a class='containerhref' href='{% url 'container_detail' pk=i.pk %}'>
          {{i.title}}
          </a>
        </LI>
        {% endfor %}
      </UL>
      {% endif %}

      {% if child_equipments %}
      <b>Оборудование</b>
      <UL>
        {% for i in child_equipments %}
        <LI>
          <a class='equipmenthref' href='{% url 'equipment_detail' pk=i.pk %}'>
          {{i.sizename.title}} № {{i.serial_number}}
          </a>
          [ {{i.in_container.title }} ]
        </LI>
        {% endfor %}
      </UL>
      {% endif %}

      {% if child_spare_parts %}
      <b>Расходные материалы</b>
      <UL>
        {% for i in child_spare_parts %}
        <LI>
          <a class='href-red' href='#'>
          {{i.title}}
          </a>
        </LI>
        {% endfor %}
      </UL>
      {% endif %}


      <center><a class="btn btn-info" href="{% url 'container_detail' pk=container.pk %}">Вернуться к карточке контейнера</a></center>


      {% else %}
      <center><h2><font color=red>ВНИМАНИЕ</font></h2></center>
      <center>Вы собираетесь удалить контейнер <b class="containerhref">{{ container.title }}</b><br>
      Удаление контейнера также повлияет на все воздействия, связанные  эти контейнером.<br>
      После удаления восстановление информации невозможно</center><br>
      <center><b>Вы уверены, что хотите продолжить?</b></center>
      <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="confirmed" value="confirmed">
        <p align=center><input class="btn btn-info" type="submit" value="Я передумал" formaction="{% url 'container_detail' pk=container.pk %}">  <input class="btn btn-danger" type="submit" value="Я понимаю последствия. Продолжить"></p>
      </form>
      {% endif %}

    </div>

{% endblock %}

mechdb_core/templates/mechdb_core/counters.html
  <meta name="yandex-verification" content="e643aa0b6af62b3f" />
  <meta name="google-site-verification" content="2vvO9uuuYIvB05wSWkEmiuyOetSRzZF4fBasjGK52i0" />

  <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter49137145 = new Ya.Metrika2({
                    id:49137145,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/tag.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks2");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/49137145" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120372027-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120372027-1');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->

mechdb_core/templates/mechdb_core/dropdown_menu.html
{% if current_user.username %}
<a class="btn btn-primary" href="{% url 'containers_map' %}" role="button">Карта</a>
<div class="btn-group">
  <button type="button" class="btn btn-danger">Просмотр</button>
  <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'action_list' %}">Последние ремонтные воздействия</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'equipment_list' %}">Список оборудования</a>
    <a class="dropdown-item" href="{% url 'sizename_list' %}">Список моделей оборудования</a>
  </div>
</div>

<div class="btn-group">
  <button type="button" class="btn btn-danger">Создание</button>
  <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'container_new' %}">Новый контейнер</a>
    <a class="dropdown-item" href="{% url 'equipment_new' %}">Новое оборудование</a>
    <a class="dropdown-item" href="{% url 'sizename_new' %}">Новая модель оборудования</a>
  </div>
</div>
{% else %}
<a class="btn btn-primary" href="{% url 'index_page' %}" role="button">Главная</a>
<a class="btn btn-danger" href="{% url 'signup' %}" role="button">Регистрация</a>
{% endif %}
<a class="btn btn-danger" href="{% url 'guide' %}" role="button">Инструкция</a>

mechdb_core/templates/mechdb_core/signup.html
{% extends 'mechdb_core/base.html' %}

{% block content %}

<div class='card_page col-md-8 col-centered'>
<center><h2>Регистрация</h2></center>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag|safe }}
      {{ field }}
        {% if field.name == "privacy_policy" %}
        Я ознакомлен с <a class="href-red" target="_blank" rel="nofollow" href="{% url 'privacy_policy' %}">Политикой конфиденциальности</a>
        {% elif field.name == "terms_of_use" %}
        Я принимаю правила <a class="href-red" target="_blank" rel="nofollow" href="{% url 'terms_of_use' %}">Пользовательского соглашения</a>
        {% endif %}
      <br>
      {% if field.help_text %}
        <p class="formhelptext">{{ field.help_text|safe }}</p>
      {% endif %}
      {% for error in field.errors %}
        <p class="formerrortext">{{ error|safe }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit" class="save">Отправить</button>
</form>
</div>
{% endblock %}

mechdb_core/templates/mechdb_core/sizename_list.html
{% extends 'mechdb_core/base.html' %}

{% block content %}

<h1><center>Список моделей</center></h1>
<div class="col-md-10 col-centered">

  <TABLE class="actionlist">
    <TR>
      <TH>Модель</TH>
      <TH width='200'>Производитель</TH>
      <TH width='200'>Поставщик</TH>
      <TH width='100'>Кол-во оборудования</TH>
    </TR>
    {% for i in sizenames %}
    <TR>
        <TD>
          <a class="href-red" href="{% url 'sizename_detail' pk=i.pk %}">
          {{i.title}}
          </a>
        </TD>
        <TD>
          {{ i.manufacturer }}
        </TD>
        <TD>
          {{ i.supply_provider }}
        </TD>
        <TD>
          {{ i.equipment_set.count }}
        </TD>
    </TR>
    {% endfor %}
  </TABLE>
</div>

{% endblock %}